name: Go

on:
  push:
    branches: [ main ]

jobs:
    -
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: go build -v

    # - name: Test
      # run: go test -v ./...

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: biliroaming-go-server-${{ github.run_number }}
        path: |
          ./biliroaming-go-server
          ./config.yaml
